Repository GaiZhenbiao/ChuanhuChatGPT, pull requests merged in 2023-03, with the labels that each got.

#149 :pencil: 完善 Nginx 和 Docker 部分教程
  README.md
Labels: documentation, docker deployment

#166 feat: 使用log代替print
  ChuanhuChatbot.py
  utils.py
Labels: 🚀 enhancement

#183 调整 UI (status_display)
  ChuanhuChatbot.py
  presets.py
Labels: 🚀 enhancement

#199 fixed token count
  utils.py
Labels: 🚀 enhancement

#135 引入 mdtex2html 更多拓展完善markdown渲染显示, resolve #134, resolve #193
  ChuanhuChatbot.py
  custom.css
  presets.py
  requirements.txt
  utils.py
Labels: 🚀 enhancement

#324 feat: 增加代码块复制功能, resolve #241
  ChuanhuChatbot.py
  assets/Kelpy-Codos.js
  assets/custom.js
  overwrites.py
Labels: 🚀 enhancement

#439 feat: 在页脚加入环境版本信息 【pull request 示例】
  ChuanhuChatbot.py
  assets/custom.css
  modules/presets.py
  modules/utils.py
Labels: 🖥️ UI

#456 Add API dollar usage and fix style 增加当月API美金使用量
  ChuanhuChatbot.py
  assets/custom.css
  modules/openai_func.py
  modules/presets.py
Labels: 🚀 enhancement

#479 Update 2-column pdf; Update new config type; Update new proxy method
  .gitignore
  ChuanhuChatbot.py
  config_example.json
  modules/chat_func.py
  modules/config.py
  modules/llama_func.py
  modules/openai_func.py
  modules/pdf_func.py
  modules/utils.py
  requirements.txt
Labels: 🚀 enhancement
