Repository GaiZhenbiao/ChuanhuChatGPT, pull requests merged in 2023-04, with the labels that each got.

#509 使用JS实现了输入框通过方向键自动填入历史信息
  ChuanhuChatbot.py
  assets/custom.js
Labels: 👍 good

#572 代码重构，支持本地model
  .gitignore
  ChuanhuChatbot.py
  configs/ds_config_chatbot.json
  modules/__init__.py
  modules/base_model.py
  modules/chat_func.py
  modules/config.py
  modules/llama_func.py
  modules/models.py
  modules/openai_func.py
  modules/presets.py
  modules/utils.py
  requirements_advanced.txt
Labels: 🚀 enhancement, 💥 BREAKING 💥

#629 doc: translate README to English
  README.md
  README_en.md
Labels: documentation

#631 Internationalization
  ChuanhuChatbot.py
  assets/custom.css
  config_example.json
  locale/en_US.json
  locale/extract_locale.py
  locale/ja_JP.json
  modules/base_model.py
  modules/config.py
  modules/models.py
  modules/presets.py
  modules/utils.py
  modules/webui_locale.py
Labels: 👍 good, 🚀 enhancement
